name: quotations
favicon: null
layout_spectrum: 0.51556
typography_spectrum: 0.29823
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#aeadbd'
    - '#586d8c'
    - '#142129'
    - '#dfd1c6'
    - '#fdf6ee'
  brandStrength: 0.5625
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
