name: quotations
favicon: null
layout_spectrum: 0.9157726904377341
typography_spectrum: 0.08337970171123743
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7488764706067741
  lightness: 0.14028571429662406
  saturation: 0.43648796644993126
  rhythmicContrast: 0.7954125604592264
purpose: []
